[unstable]
build-std = ['std', 'panic_abort']

[target.wasm32-unknown-unknown]
rustflags = [
    '-Ctarget-feature=+atomics,+bulk-memory',
    "-C",
    "link-arg=--shared-memory",
    "-C",
    "link-arg=--import-memory",
    "-C",
    "link-arg=--max-memory=1073741824",
    "-C",
    "link-arg=--export=__wasm_init_tls",
    "-C",
    "link-arg=--export=__tls_size",
    "-C",
    "link-arg=--export=__tls_align",
    "-C",
    "link-arg=--export=__tls_base",
    '--cfg',
    'getrandom_backend="wasm_js"',
]
