use raug::prelude::*;

// this macro generates a processor struct and implements the Processor trait for it based on the function signature and body
// the generated struct will have the name of the function converted to UpperCamelCase
// e.g. `sine_oscillator` will become `SineOscillator`
// the original function is also output by the macro for convenience and linting :)
#[processor]
pub fn sine_oscillator(
    env: ProcEnv,             // information about the processing context
    #[state] phase: &mut f32, // stateful parameter that is preserved across calls
    #[input] freq: &f32,      // input frequency
    #[output] out: &mut f32,  // output sine wave
) -> ProcResult<()> {
    *phase += 2.0 * std::f32::consts::PI * freq / env.sample_rate;
    *out = phase.sin() * 0.2;
    Ok(())
}

// we can add additional functionality to the processor struct generated by the #[processor] macro
impl SineOscillator {
    fn new() -> Self {
        SineOscillator {
            phase: 0.0,
            freq: 440.0,
            out: 0.0,
        }
    }
}

fn main() {
    // initialize logging
    env_logger::init();

    // create a new graph
    let graph = Graph::new();

    // add some outputs
    let out1 = graph.add_audio_output();
    let out2 = graph.add_audio_output();

    // add a sine oscillator
    let sine = graph.add(SineOscillator::new());

    // connect the sine oscillator to the outputs
    sine.output(0).connect(&out1.input(0));
    sine.output(0).connect(&out2.input(0));

    // open the audio stream
    let mut stream = CpalStream::default();
    // run the graph
    stream.spawn(&graph).unwrap();
    stream.play().unwrap();
    std::thread::sleep(std::time::Duration::from_secs(60));
    stream.stop().unwrap();
}
